owner: keywordnew
repo: helsinki-watchtower
user-agent: keywordnew

sites:
  - name: Helsinki Region Environmental Services HSY
    url: https://www.hsy.fi/en/water-and-sewers/
    method: GET
    icon: https://nilspace.xyz/content/images/2023/05/water.png
  - name: Helen Oy
    url: https://www.helen.fi/en
    method: GET
    icon: https://nilspace.xyz/content/images/2023/05/power-1.png
  - name: Elisa Oyj
    url: https://verkkoasiointi.elisa.fi/
    method: GET
    icon: https://nilspace.xyz/content/images/2023/05/communication.png
  - name: Helsingin ja Uudenmaan sairaanhoitopiiri
    url: https://www.hus.fi/potilaalle/sairaalat-ja-toimipisteet/paivystysapu-116117
    method: GET
    icon: https://nilspace.xyz/content/images/2023/05/hospital.png
  - name: Helsinki Police Department
    url: https://poliisi.fi/tee-rikosilmoitus
    method: GET
    icon: https://nilspace.xyz/content/images/2023/05/emergency.png
  - name: Helsinki Regional Transport Authority
    url: https://www.hsl.fi/
    method: GET
    icon: https://nilspace.xyz/content/images/2023/05/transportation-1.png
  - name: OP Financial Group
    url: https://www.op.fi/home-page
    method: GET
    icon: https://nilspace.xyz/content/images/2023/05/payment.png


status-website:
  baseUrl: /helsinki-watchtower
  name: 'Neighbourhood Cyber'
  logoUrl: https://nilspace.xyz/content/images/2023/05/favicon.png
  favicon: https://nilspace.xyz/content/images/2023/05/favicon.png
  introTitle: 'Helsinki 🇫🇮 watchtower'
  introMessage: 'check if critical infrastructure may be down, or use GitHub ↗️ to "Watch" and get notified'
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
    - title: Neighbourhoods
      href: https://github.com/$OWNER?tab=repositories&q=watchtower
      
i18n:
  footer: This Watchtower is part of [Project Watchtower](https://nilspace.xyz/project-watchtower/).
